# Generated by Django 4.0.1 on 2022-01-15 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='pic')),
                ('price', models.FloatField(max_length=30)),
                ('manufdate', models.DateField(null=True)),
                ('expirydate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Userans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qans1', models.CharField(max_length=200)),
                ('qans2', models.CharField(max_length=200)),
                ('qans3', models.CharField(max_length=200)),
                ('username', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='customer.register')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payid', models.IntegerField(default='null')),
                ('mode', models.CharField(default='Cash on delivery', max_length=30)),
                ('discount', models.IntegerField(choices=[(0, '10%'), (1, '50%'), (2, '80%')], default=0)),
                ('price', models.FloatField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.register')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qans1', models.CharField(max_length=200)),
                ('qans2', models.CharField(max_length=200)),
                ('qans3', models.CharField(max_length=200)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.detail')),
            ],
        ),
        migrations.CreateModel(
            name='delivery_details',
            fields=[
                ('fullname', models.CharField(max_length=30)),
                ('contact', models.BigIntegerField()),
                ('address', models.TextField()),
                ('Orderno', models.IntegerField(primary_key=True, serialize=False)),
                ('Orderdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('deliverydate', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.register')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.question')),
            ],
        ),
    ]
