# Generated by Django 4.0.1 on 2022-01-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_options_qans4_userans_qans4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
