# Generated by Django 4.0.1 on 2022-01-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='pname',
            field=models.CharField(max_length=30),
        ),
    ]
