# Generated by Django 4.0.1 on 2022-01-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_detail_pname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='delivery_details',
            new_name='order',
        ),
    ]
