# Generated by Django 4.0.1 on 2022-03-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_rename_username_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
