# Generated by Django 4.0.1 on 2022-03-28 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userans',
            name='username',
        ),
    ]
